[Fix] The only selected accordion will be opened when Enter or Space pressed
Fliplet/fliplet-widget-accordion-start pull request #22
Opened 2020-08-27 06:18 UTC by YaroslavOvdii

@sofiiakvasnevska 

## Issue
https://weboo.atlassian.net/browse/OD-27

## Description
The only selected accordion will be opened when Enter or Space pressed

## Screenshots/screencasts
https://share.getcloudapp.com/jkuZXqrA

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko

2020-08-27 10:02 UTC, tonytlwu requested changes

2020-08-27 10:02 UTC, tonytlwu commented on js/build.js
> +        $(event.target).find('.collapse').collapse('toggle');
```suggestion
        $(event.target).find(Collapsible.SELECTORS.collapse).collapse('toggle');
```

2020-08-28 07:58 UTC, YaroslavOvdii commented on js/build.js
> +        $(event.target).find('.collapse').collapse('toggle');
@tonytlwu Fixed

2020-09-01 09:26 UTC, tonytlwu approved these changes
@sofiiakvasnevska This is ready for testing

Risk: Low
Affected: Accordions
Verify: Accordions open and close correctly with mouse, touch and keyboard

2020-09-01 09:54 UTC, merged